### ISSUE TITLE
Start video recording failed

### ISSUE THREAD

**Issue by fezrestia** [fezrestia/view-finder-anywhere#40]
Start rec will be failed.

logcat shows following crash log
maybe permission configuration is not correct.

------------
Fatal Exception: java.lang.UnsupportedOperationException: Cannot create AudioRecord
       at android.media.AudioRecord$Builder.build(AudioRecord.java:775)
       at com.fezrestia.android.viewfinderanywhere.device.codec.MpegRecorder.setup(MpegRecorder.kt:160)
       at com.fezrestia.android.viewfinderanywhere.control.OverlayViewFinderController$StateRec.entry(OverlayViewFinderController.kt:901)
       at com.fezrestia.android.viewfinderanywhere.control.OverlayViewFinderController.changeStateTo(OverlayViewFinderController.kt:419)
       at com.fezrestia.android.viewfinderanywhere.control.OverlayViewFinderController.access$changeStateTo(OverlayViewFinderController.kt:39)
       at com.fezrestia.android.viewfinderanywhere.control.OverlayViewFinderController$StateIdle.requestStartRec(OverlayViewFinderController.kt:724)
       at com.fezrestia.android.viewfinderanywhere.view.OverlayViewFinderRootView.dispatchKeyEvent(OverlayViewFinderRootView.kt:1047)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5954)
-----------

**Comment by fezrestia** [comment]
9a45f6221af6764fd4b4e63cb7269e2c9ba9b947
